// flow-typed signature: 517cf29265e65c5b6cd20fc50a5c02e3
// flow-typed version: <<STUB>>/@fortawesome/free-brands-svg-icons_v5.13.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/free-brands-svg-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/free-brands-svg-icons' {
  declare module.exports: any;
}
