// flow-typed signature: a82ee3c2afa4cddcd968fa73bbeba7c3
// flow-typed version: <<STUB>>/babel-polyfill_v6.26.0/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-polyfill' {
  declare module.exports: any;
}
