// flow-typed signature: 7b9989a73d9f5421207c9bee4141af44
// flow-typed version: <<STUB>>/date-fns_v1.29.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'date-fns' {
  declare module.exports: any;
}
