// flow-typed signature: b1c6c31acffa4402c5f7a3611489836c
// flow-typed version: <<STUB>>/lattice-ui-kit_v0.38.0/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice-ui-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice-ui-kit' {
  declare module.exports: any;
}
